resource-pack:
  enable: true
  public-url: ""
  port: 8173
  path: "Infuse Pack.zip"
infuses:
  strength:
    passive:
      action-bar-active: "\uE014"
      action-bar-inactive: "\uE002"
      primary-color-active: "&4&l"
      primary-color-inactive: "&f&l"
      bonus-damage-below-6-hearts: 1.0
      bonus-damage-below-4-hearts: 4.0
      bonus-damage-below-2-hearts: 6.0
    spark:
      cooldown-start-minutes: 0
      cooldown-start-seconds: 10
      duration-seconds: 10
      cooldown-end-minutes: 1
      cooldown-end-seconds: 0
  heart:
    passive:
      action-bar-active: "\uE015"
      action-bar-inactive: "\uE003"
      primary-color-active: "&5&l"
      primary-color-inactive: "&f&l"
      max-health: 6.0
    spark:
      max-health: 6.0
      cooldown-start-minutes: 1
      cooldown-start-seconds: 20
      duration-seconds: 80
      cooldown-end-minutes: 2
      cooldown-end-seconds: 0
  haste:
    passive:
      action-bar-active: "\uE016"
      action-bar-inactive: "\uE004"
      primary-color-active: "&6&l"
      primary-color-inactive: "&f&l"
      potion-level: 2
      potion-duration-seconds: 2
      potion-particles: false
      potion-icon: false
      extra-drop-materials:
        - DIAMOND_ORE
        - DEEPSLATE_DIAMOND_ORE
        - COAL_ORE
        - DEEPSLATE_COAL_ORE
        - GOLD_ORE
        - DEEPSLATE_GOLD_ORE
        - IRON_ORE
        - DEEPSLATE_IRON_ORE
        - EMERALD_ORE
        - DEEPSLATE_EMERALD_ORE
        - LAPIS_ORE
        - DEEPSLATE_LAPIS_ORE
        - REDSTONE_ORE
        - DEEPSLATE_REDSTONE_ORE
        - COPPER_ORE
        - DEEPSLATE_COPPER_ORE
        - NETHER_GOLD_ORE
        - NETHER_QUARTZ_ORE
        - AMETHYST_CLUSTER
    spark:
      potion-level: 255
      potion-duration-seconds: 45
      potion-particles: false
      potion-icon: false
      cooldown-start-minutes: 0
      cooldown-start-seconds: 45
      duration-seconds: 45
      cooldown-end-minutes: 1
      cooldown-end-seconds: 15
  ninja:
    passive:
      action-bar-active: "\uE017"
      action-bar-inactive: "\uE005"
      primary-color-active: "&5&l"
      primary-color-inactive: "&f&l"
      potion-level: 1
      potion-duration-seconds: 2
      potion-particles: false
      potion-icon: true
      still-seconds: 5
      true-duration-seconds: 4
      cooldown-seconds: 0
      passive-damage-bonus: 0.3
      activation-sound: "BLOCK_AMETHYST_BLOCK_CHIME"
      activation-sound-volume: 1.0
      activation-sound-pitch: 1.2
      speed-level: 3
      speed-burst-seconds: 4
      speed-particles: false
      speed-icon: true
    spark:
      cooldown-start-minutes: 0
      cooldown-start-seconds: 15
      duration-seconds: 15
      cooldown-end-minutes: 1
      cooldown-end-seconds: 30
      outgoing-damage-bonus: 0.5
      incoming-damage-bonus: 0.9
      particle-count: 8
      particle-offset: 0.2
      speed-level: 3
      speed-burst-seconds: 4
      speed-particles: false
      speed-icon: true
  feather:
    passive:
      action-bar-active: "\uE018"
      action-bar-inactive: "\uE006"
      primary-color-active: "&2&l"
      primary-color-inactive: "&f&l"
      levitation-chance: 0.05
      levitation-duration-seconds: 2.0
      levitation-amplifier: 2
      levitation-particles: false
      levitation-icon: false
    spark:
      cooldown-start-minutes: 0
      cooldown-start-seconds: 9
      duration-seconds: 9
      levitation-radius: 8.0
      cycles: 3
      levitation-duration-seconds: 2.0
      drop-duration-seconds: 0.7
      levitation-amplifier: 2
      levitation-particles: false
      levitation-icon: false
      cooldown-end-minutes: 0
      cooldown-end-seconds: 30
  frost:
    passive:
      action-bar-active: "\uE019"
      action-bar-inactive: "\uE007"
      primary-color-active: "&b&l"
      primary-color-inactive: "&f&l"
      scan-radius-xz: 2
      scan-radius-y: 1
      ice-materials:
        - ICE
        - BLUE_ICE
        - PACKED_ICE
      snow-materials:
        - SNOW
        - SNOW_BLOCK
      ice-speed-level: 10
      ice-speed-duration-seconds: 2
      ice-speed-particles: false
      ice-speed-icon: false
      snow-speed-level: 3
      snow-speed-duration-seconds: 2
      snow-speed-particles: false
      snow-speed-icon: false
    spark:
      cooldown-start-minutes: 0
      cooldown-start-seconds: 30
      duration-seconds: 30
      cooldown-end-minutes: 1
      cooldown-end-seconds: 0
      bonus-damage-freeze-threshold-ticks: 20
      bonus-damage: 3.0
      freeze-ticks: 600
  thunder:
    passive:
      action-bar-active: "\uE020"
      action-bar-inactive: "\uE008"
      primary-color-active: "&9&l"
      primary-color-inactive: "&f&l"
      hits-to-strike: 10
    spark:
      cooldown-start-minutes: 0
      cooldown-start-seconds: 10
      lightning-radius: 8
      cooldown-end-minutes: 1
      cooldown-end-seconds: 20
  regeneration:
    passive:
      action-bar-active: "\uE021"
      action-bar-inactive: "\uE009"
      primary-color-active: "&c&l"
      primary-color-inactive: "&f&l"
      hit-potion-level: 2
      hit-potion-duration-seconds: 1
      hit-potion-particles: false
      hit-potion-icon: false
    spark:
      cooldown-start-minutes: 0
      cooldown-start-seconds: 20
      duration-seconds: 20
      heal-percent: 0.25
      cooldown-end-minutes: 1
      cooldown-end-seconds: 10
  pig:
    passive:
      action-bar-active: "\uE027"
      action-bar-inactive: "\uE026"
      primary-color-active: "&d&l"
      primary-color-inactive: "&f&l"
      knockback-resistance: 0.05
      speed-hit-threshold: 5
      speed-level: 3
      speed-duration-seconds: 5
      speed-particles: false
      speed-icon: false
    spark:
      cooldown-start-minutes: 0
      cooldown-start-seconds: 50
      duration-seconds: 50
      cooldown-end-minutes: 1
      cooldown-end-seconds: 20
      sound-volume: 1.0
      sound-pitch: 1.2
      trigger-health: 8.0
      leave-health: 1.0
      heal-amount: 10.0
  piglin:
    passive:
      action-bar-active: "\uE029"
      action-bar-inactive: "\uE028"
      primary-color-active: "&4&l"
      primary-color-inactive: "&4&l"
      mark-window-ticks: 40
      mark-cooldown-seconds: 4
      bonus-damage: 1.25
    spark:
      cooldown-start-minutes: 0
      cooldown-start-seconds: 30
      duration-seconds: 30
      cooldown-end-minutes: 1
      cooldown-end-seconds: 0
      mark-cooldown-seconds: 2
      bonus-damage: 1.8
      sound-volume: 1.0
      sound-pitch: 1.0
      particle-count: 20
  overdrive:
    passive:
      action-bar-active: "\uE031"
      action-bar-inactive: "\uE030"
      primary-color-active: "&b&l"
      primary-color-inactive: "&f&l"
      mirror-chance: 0.4
      echo-damage-multiplier: 0.8
    spark:
      cooldown-start-minutes: 0
      cooldown-start-seconds: 6
      duration-seconds: 6
      cooldown-end-minutes: 1
      cooldown-end-seconds: 0
      mirror-chance: 1.0
      echo-damage-multiplier: 0.9
  ocean:
    passive:
      action-bar-active: "\uE022&9&l"
      action-bar-inactive: "\uE010&f&l"
      salted-duration-seconds: 3
      salted-damage-increase-percent: 5.0
    spark:
      cooldown-start-minutes: 0
      cooldown-start-seconds: 30
      wave-max-radius: 9.0
      wave-max-height: 8
      wave-expansion-step: 1.0
      wave-tick-interval-ticks: 2
      wave-knockback-horizontal: 1.25
      wave-knockback-vertical: 0.35
      cooldown-end-minutes: 1
      cooldown-end-seconds: 0
  fire:
    passive:
      action-bar-active: "\uE023&6&l"
      action-bar-inactive: "\uE011&f&l"
      hits-to-ignite: 10
      ignite-duration-seconds: 4
      ignited-true-damage-hearts: 0.5
    spark:
      cooldown-start-minutes: 0
      cooldown-start-seconds: 30
      duration-seconds: 1
      fireball-true-damage-hearts: 3.5
      fireball-ignite-radius: 4.5
      fireball-speed: 1.0
      cooldown-end-minutes: 1
      cooldown-end-seconds: 0
  emerald:
    passive:
      action-bar-active: "\uE024&a&l"
      action-bar-inactive: "\uE012&f&l"
      potion-level: 3
      potion-duration-seconds: 2
      potion-particles: false
      potion-icon: false
    spark:
      cooldown-start-minutes: 1
      cooldown-start-seconds: 30
      duration-seconds: 90
      potion-level: 200
      potion-duration-seconds: 90
      potion-particles: false
      potion-icon: false
      cooldown-end-minutes: 5
      cooldown-end-seconds: 0
  speed:
    passive:
      action-bar-active: "\uE025&e&l"
      action-bar-inactive: "\uE013&f&l"
      potion-level: 2
      potion-duration-seconds: 2
      potion-particles: false
      potion-icon: false
    spark:
      cooldown-start-minutes: 0
      cooldown-start-seconds: 1
      duration-seconds: 1
      velocity-multiplier: 2.0
      cooldown-end-minutes: 0
      cooldown-end-seconds: 15
